version: "3"
services:
  webserver:
    build: .
    container_name: webserver
    tty: true
    privileged: true

  database:
    build: .
    ports:
      - "8080:80"
    container_name: database
    tty: true
    privileged: true